version: "2.2"
services:
        nextcloud:
          image: wonderfall/nextcloud
          container_name: dc_nextcloud
          depends_on:
            nextcloud-db:
              condition: service_healthy
          links:
            - nextcloud-db:dc_nextcloud_db             # If using MySQL
#            - solr:dc_solr                   # If using Nextant
            - redis:dc_redis                 # If using Redis
          environment:
            - UID=1000
            - GID=1000
            - UPLOAD_MAX_SIZE=10G
            - APC_SHM_SIZE=128M
            - OPCACHE_MEM_SIZE=128
            - CRON_PERIOD=15m
            - TZ=Europe/Berlin
            - ADMIN_USER=${NEXTCLOUD_ADMIN}
            - ADMIN_PASSWORD=${NEXTCLOUD_PASS}
            - DOMAIN=${PUBLIC_FQDN}
            - DB_TYPE=mysql
            - DB_NAME=${DBNAME}
            - DB_USER=${DBUSER}
            - DB_PASSWORD=${DBPASS}
            - DB_HOST=dc_nextcloud_db
            - VIRTUAL_HOST=${PUBLIC_FQDN}
            - VIRTUAL_PORT=${HTTP_PORT:-8888}
            - LETSENCRYPT_HOST=${PUBLIC_FQDN}
            - LETSENCRYPT_EMAIL=${ADMIN_MAIL}
          volumes:
            - ./data/nextcloud/data:/data
            - ./data/nextcloud/config:/config
            - ./data/nextcloud/apps:/apps2
            - ./data/nextcloud/themes:/nextcloud/themes
#          ports:
#             - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-8888}:${HTTP_PORT:-8888}"

        # If using MySQL
        nextcloud-db:
          image: mariadb:10
          container_name: dc_nextcloud_db
          healthcheck:
            test: ["CMD", "mysqladmin", "ping", "--host", "localhost", "--silent"]
            interval: 5s
            timeout: 5s
            retries: 10
          volumes:
            - ./data/nextcloud/db:/var/lib/mysql
          environment:
            - MYSQL_ROOT_PASSWORD=${DBROOT}
            - MYSQL_DATABASE=${DBNAME}
            - MYSQL_USER=${DBUSER}
            - MYSQL_PASSWORD=${DBPASS}

#        # If using Nextant
#        solr:
#          image: solr:6-alpine
#          container_name: dc_nextcloud_solr
#          volumes:
#            - ./data/solr:/opt/solr/server/solr/mycores
#          entrypoint:
#            - docker-entrypoint.sh
#            - solr-precreate
#            - nextant

        # If using Redis
        redis:
          image: redis:alpine
          container_name: dc_nextcloud_redis
          volumes:
            - ./data/redis:/data
